/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiVectorArrangeBelow: typeof import('~icons/mdi/vector-arrange-below')['default']
  }
}
